// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lag.proto
// Protobuf C++ Version: 5.26.1

#include "lag.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Net {

inline constexpr Lag::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Lag::Lag(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct LagDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LagDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LagDefaultTypeInternal() {}
  union {
    Lag _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LagDefaultTypeInternal _Lag_default_instance_;

inline constexpr LagMember::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : members_{},
        lag_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LagMember::LagMember(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct LagMemberDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LagMemberDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LagMemberDefaultTypeInternal() {}
  union {
    LagMember _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LagMemberDefaultTypeInternal _LagMember_default_instance_;
}  // namespace Net
static ::_pb::Metadata file_level_metadata_lag_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_lag_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_lag_2eproto = nullptr;
const ::uint32_t
    TableStruct_lag_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Net::Lag, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Net::Lag, _impl_.id_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Net::LagMember, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Net::LagMember, _impl_.lag_id_),
        PROTOBUF_FIELD_OFFSET(::Net::LagMember, _impl_.members_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Net::Lag)},
        {9, -1, -1, sizeof(::Net::LagMember)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::Net::_Lag_default_instance_._instance,
    &::Net::_LagMember_default_instance_._instance,
};
const char descriptor_table_protodef_lag_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\tlag.proto\022\003Net\032\014common.proto\032\017interfac"
    "e.proto\"\021\n\003Lag\022\n\n\002id\030\001 \001(\t\"8\n\tLagMember\022"
    "\016\n\006lag_id\030\001 \001(\t\022\033\n\007members\030\002 \003(\0132\n.Net.I"
    "face2\274\001\n\rLagManagement\022$\n\tCreateLag\022\010.Ne"
    "t.Lag\032\013.Net.Result\"\000\022$\n\tDeleteLag\022\010.Net."
    "Lag\032\013.Net.Result\"\000\022-\n\014AddLagMember\022\016.Net"
    ".LagMember\032\013.Net.Result\"\000\0220\n\017RemoveLagMe"
    "mber\022\016.Net.LagMember\032\013.Net.Result\"\000b\006pro"
    "to3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_lag_2eproto_deps[2] =
    {
        &::descriptor_table_common_2eproto,
        &::descriptor_table_interface_2eproto,
};
static ::absl::once_flag descriptor_table_lag_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_lag_2eproto = {
    false,
    false,
    323,
    descriptor_table_protodef_lag_2eproto,
    "lag.proto",
    &descriptor_table_lag_2eproto_once,
    descriptor_table_lag_2eproto_deps,
    2,
    2,
    schemas,
    file_default_instances,
    TableStruct_lag_2eproto::offsets,
    file_level_metadata_lag_2eproto,
    file_level_enum_descriptors_lag_2eproto,
    file_level_service_descriptors_lag_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_lag_2eproto_getter() {
  return &descriptor_table_lag_2eproto;
}
namespace Net {
// ===================================================================

class Lag::_Internal {
 public:
};

Lag::Lag(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Net.Lag)
}
inline PROTOBUF_NDEBUG_INLINE Lag::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : id_(arena, from.id_),
        _cached_size_{0} {}

Lag::Lag(
    ::google::protobuf::Arena* arena,
    const Lag& from)
    : ::google::protobuf::Message(arena) {
  Lag* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:Net.Lag)
}
inline PROTOBUF_NDEBUG_INLINE Lag::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : id_(arena),
        _cached_size_{0} {}

inline void Lag::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Lag::~Lag() {
  // @@protoc_insertion_point(destructor:Net.Lag)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Lag::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.id_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Lag::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(Lag, _impl_._cached_size_),
              false,
          },
          &Lag::MergeImpl,
          &Lag::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void Lag::Clear() {
// @@protoc_insertion_point(message_clear_start:Net.Lag)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Lag::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 18, 2> Lag::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Lag_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Net::Lag>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Lag, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string id = 1;
    {PROTOBUF_FIELD_OFFSET(Lag, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\7\2\0\0\0\0\0\0"
    "Net.Lag"
    "id"
  }},
};

::uint8_t* Lag::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Net.Lag)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string id = 1;
  if (!this->_internal_id().empty()) {
    const std::string& _s = this->_internal_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Net.Lag.id");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Net.Lag)
  return target;
}

::size_t Lag::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Net.Lag)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string id = 1;
  if (!this->_internal_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Lag::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Lag*>(&to_msg);
  auto& from = static_cast<const Lag&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Net.Lag)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_id().empty()) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Lag::CopyFrom(const Lag& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Net.Lag)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Lag::IsInitialized() const {
  return true;
}

void Lag::InternalSwap(Lag* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
}

::google::protobuf::Metadata Lag::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_lag_2eproto_getter,
                                   &descriptor_table_lag_2eproto_once,
                                   file_level_metadata_lag_2eproto[0]);
}
// ===================================================================

class LagMember::_Internal {
 public:
};

void LagMember::clear_members() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.members_.Clear();
}
LagMember::LagMember(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Net.LagMember)
}
inline PROTOBUF_NDEBUG_INLINE LagMember::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : members_{visibility, arena, from.members_},
        lag_id_(arena, from.lag_id_),
        _cached_size_{0} {}

LagMember::LagMember(
    ::google::protobuf::Arena* arena,
    const LagMember& from)
    : ::google::protobuf::Message(arena) {
  LagMember* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:Net.LagMember)
}
inline PROTOBUF_NDEBUG_INLINE LagMember::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : members_{visibility, arena},
        lag_id_(arena),
        _cached_size_{0} {}

inline void LagMember::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
LagMember::~LagMember() {
  // @@protoc_insertion_point(destructor:Net.LagMember)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void LagMember::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.lag_id_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
LagMember::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(LagMember, _impl_._cached_size_),
              false,
          },
          &LagMember::MergeImpl,
          &LagMember::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void LagMember::Clear() {
// @@protoc_insertion_point(message_clear_start:Net.LagMember)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.members_.Clear();
  _impl_.lag_id_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* LagMember::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 28, 2> LagMember::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_LagMember_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Net::LagMember>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .Net.Iface members = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(LagMember, _impl_.members_)}},
    // string lag_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(LagMember, _impl_.lag_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string lag_id = 1;
    {PROTOBUF_FIELD_OFFSET(LagMember, _impl_.lag_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated .Net.Iface members = 2;
    {PROTOBUF_FIELD_OFFSET(LagMember, _impl_.members_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Net::Iface>()},
  }}, {{
    "\15\6\0\0\0\0\0\0"
    "Net.LagMember"
    "lag_id"
  }},
};

::uint8_t* LagMember::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Net.LagMember)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string lag_id = 1;
  if (!this->_internal_lag_id().empty()) {
    const std::string& _s = this->_internal_lag_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Net.LagMember.lag_id");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // repeated .Net.Iface members = 2;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_members_size());
       i < n; i++) {
    const auto& repfield = this->_internal_members().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            2, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Net.LagMember)
  return target;
}

::size_t LagMember::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Net.LagMember)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Net.Iface members = 2;
  total_size += 1UL * this->_internal_members_size();
  for (const auto& msg : this->_internal_members()) {
    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // string lag_id = 1;
  if (!this->_internal_lag_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_lag_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void LagMember::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<LagMember*>(&to_msg);
  auto& from = static_cast<const LagMember&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Net.LagMember)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_members()->MergeFrom(
      from._internal_members());
  if (!from._internal_lag_id().empty()) {
    _this->_internal_set_lag_id(from._internal_lag_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LagMember::CopyFrom(const LagMember& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Net.LagMember)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool LagMember::IsInitialized() const {
  return true;
}

void LagMember::InternalSwap(LagMember* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.members_.InternalSwap(&other->_impl_.members_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.lag_id_, &other->_impl_.lag_id_, arena);
}

::google::protobuf::Metadata LagMember::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_lag_2eproto_getter,
                                   &descriptor_table_lag_2eproto_once,
                                   file_level_metadata_lag_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Net
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::std::false_type _static_init_ PROTOBUF_UNUSED =
    (::_pbi::AddDescriptors(&descriptor_table_lag_2eproto),
     ::std::false_type{});
#include "google/protobuf/port_undef.inc"
