// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vlan.proto
// Protobuf C++ Version: 5.26.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_vlan_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_vlan_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION != 5026001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "common.pb.h"
#include "port.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_vlan_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_vlan_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_vlan_2eproto;
namespace Net {
class VlanInstance;
struct VlanInstanceDefaultTypeInternal;
extern VlanInstanceDefaultTypeInternal _VlanInstance_default_instance_;
class VlanMember;
struct VlanMemberDefaultTypeInternal;
extern VlanMemberDefaultTypeInternal _VlanMember_default_instance_;
}  // namespace Net
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Net {

// ===================================================================


// -------------------------------------------------------------------

class VlanInstance final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Net.VlanInstance) */ {
 public:
  inline VlanInstance() : VlanInstance(nullptr) {}
  ~VlanInstance() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR VlanInstance(
      ::google::protobuf::internal::ConstantInitialized);

  inline VlanInstance(const VlanInstance& from) : VlanInstance(nullptr, from) {}
  inline VlanInstance(VlanInstance&& from) noexcept
      : VlanInstance(nullptr, std::move(from)) {}
  inline VlanInstance& operator=(const VlanInstance& from) {
    CopyFrom(from);
    return *this;
  }
  inline VlanInstance& operator=(VlanInstance&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VlanInstance& default_instance() {
    return *internal_default_instance();
  }
  static inline const VlanInstance* internal_default_instance() {
    return reinterpret_cast<const VlanInstance*>(
        &_VlanInstance_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(VlanInstance& a, VlanInstance& b) { a.Swap(&b); }
  inline void Swap(VlanInstance* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VlanInstance* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VlanInstance* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<VlanInstance>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const VlanInstance& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const VlanInstance& from) { VlanInstance::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(VlanInstance* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "Net.VlanInstance"; }

 protected:
  explicit VlanInstance(::google::protobuf::Arena* arena);
  VlanInstance(::google::protobuf::Arena* arena, const VlanInstance& from);
  VlanInstance(::google::protobuf::Arena* arena, VlanInstance&& from) noexcept
      : VlanInstance(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 1,
  };
  // string id = 1;
  void clear_id() ;
  const std::string& id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_id(Arg_&& arg, Args_... args);
  std::string* mutable_id();
  PROTOBUF_NODISCARD std::string* release_id();
  void set_allocated_id(std::string* value);

  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(
      const std::string& value);
  std::string* _internal_mutable_id();

  public:
  // @@protoc_insertion_point(class_scope:Net.VlanInstance)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      27, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr id_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_vlan_2eproto;
};
// -------------------------------------------------------------------

class VlanMember final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Net.VlanMember) */ {
 public:
  inline VlanMember() : VlanMember(nullptr) {}
  ~VlanMember() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR VlanMember(
      ::google::protobuf::internal::ConstantInitialized);

  inline VlanMember(const VlanMember& from) : VlanMember(nullptr, from) {}
  inline VlanMember(VlanMember&& from) noexcept
      : VlanMember(nullptr, std::move(from)) {}
  inline VlanMember& operator=(const VlanMember& from) {
    CopyFrom(from);
    return *this;
  }
  inline VlanMember& operator=(VlanMember&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VlanMember& default_instance() {
    return *internal_default_instance();
  }
  static inline const VlanMember* internal_default_instance() {
    return reinterpret_cast<const VlanMember*>(
        &_VlanMember_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(VlanMember& a, VlanMember& b) { a.Swap(&b); }
  inline void Swap(VlanMember* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VlanMember* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VlanMember* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<VlanMember>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const VlanMember& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const VlanMember& from) { VlanMember::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(VlanMember* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "Net.VlanMember"; }

 protected:
  explicit VlanMember(::google::protobuf::Arena* arena);
  VlanMember(::google::protobuf::Arena* arena, const VlanMember& from);
  VlanMember(::google::protobuf::Arena* arena, VlanMember&& from) noexcept
      : VlanMember(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMembersFieldNumber = 2,
    kLagFieldNumber = 1,
  };
  // repeated .Net.Port members = 2;
  int members_size() const;
  private:
  int _internal_members_size() const;

  public:
  void clear_members() ;
  ::Net::Port* mutable_members(int index);
  ::google::protobuf::RepeatedPtrField<::Net::Port>* mutable_members();

  private:
  const ::google::protobuf::RepeatedPtrField<::Net::Port>& _internal_members() const;
  ::google::protobuf::RepeatedPtrField<::Net::Port>* _internal_mutable_members();
  public:
  const ::Net::Port& members(int index) const;
  ::Net::Port* add_members();
  const ::google::protobuf::RepeatedPtrField<::Net::Port>& members() const;
  // .Net.VlanInstance lag = 1;
  bool has_lag() const;
  void clear_lag() ;
  const ::Net::VlanInstance& lag() const;
  PROTOBUF_NODISCARD ::Net::VlanInstance* release_lag();
  ::Net::VlanInstance* mutable_lag();
  void set_allocated_lag(::Net::VlanInstance* value);
  void unsafe_arena_set_allocated_lag(::Net::VlanInstance* value);
  ::Net::VlanInstance* unsafe_arena_release_lag();

  private:
  const ::Net::VlanInstance& _internal_lag() const;
  ::Net::VlanInstance* _internal_mutable_lag();

  public:
  // @@protoc_insertion_point(class_scope:Net.VlanMember)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 2,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::Net::Port > members_;
    ::Net::VlanInstance* lag_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_vlan_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// VlanInstance

// string id = 1;
inline void VlanInstance::clear_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.id_.ClearToEmpty();
}
inline const std::string& VlanInstance::id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Net.VlanInstance.id)
  return _internal_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VlanInstance::set_id(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Net.VlanInstance.id)
}
inline std::string* VlanInstance::mutable_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:Net.VlanInstance.id)
  return _s;
}
inline const std::string& VlanInstance::_internal_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.id_.Get();
}
inline void VlanInstance::_internal_set_id(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.id_.Set(value, GetArena());
}
inline std::string* VlanInstance::_internal_mutable_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.id_.Mutable( GetArena());
}
inline std::string* VlanInstance::release_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:Net.VlanInstance.id)
  return _impl_.id_.Release();
}
inline void VlanInstance::set_allocated_id(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.id_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.id_.IsDefault()) {
          _impl_.id_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Net.VlanInstance.id)
}

// -------------------------------------------------------------------

// VlanMember

// .Net.VlanInstance lag = 1;
inline bool VlanMember::has_lag() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.lag_ != nullptr);
  return value;
}
inline void VlanMember::clear_lag() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.lag_ != nullptr) _impl_.lag_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::Net::VlanInstance& VlanMember::_internal_lag() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::Net::VlanInstance* p = _impl_.lag_;
  return p != nullptr ? *p : reinterpret_cast<const ::Net::VlanInstance&>(::Net::_VlanInstance_default_instance_);
}
inline const ::Net::VlanInstance& VlanMember::lag() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Net.VlanMember.lag)
  return _internal_lag();
}
inline void VlanMember::unsafe_arena_set_allocated_lag(::Net::VlanInstance* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.lag_);
  }
  _impl_.lag_ = reinterpret_cast<::Net::VlanInstance*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Net.VlanMember.lag)
}
inline ::Net::VlanInstance* VlanMember::release_lag() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Net::VlanInstance* released = _impl_.lag_;
  _impl_.lag_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::Net::VlanInstance* VlanMember::unsafe_arena_release_lag() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:Net.VlanMember.lag)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Net::VlanInstance* temp = _impl_.lag_;
  _impl_.lag_ = nullptr;
  return temp;
}
inline ::Net::VlanInstance* VlanMember::_internal_mutable_lag() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.lag_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Net::VlanInstance>(GetArena());
    _impl_.lag_ = reinterpret_cast<::Net::VlanInstance*>(p);
  }
  return _impl_.lag_;
}
inline ::Net::VlanInstance* VlanMember::mutable_lag() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::Net::VlanInstance* _msg = _internal_mutable_lag();
  // @@protoc_insertion_point(field_mutable:Net.VlanMember.lag)
  return _msg;
}
inline void VlanMember::set_allocated_lag(::Net::VlanInstance* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete (_impl_.lag_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.lag_ = reinterpret_cast<::Net::VlanInstance*>(value);
  // @@protoc_insertion_point(field_set_allocated:Net.VlanMember.lag)
}

// repeated .Net.Port members = 2;
inline int VlanMember::_internal_members_size() const {
  return _internal_members().size();
}
inline int VlanMember::members_size() const {
  return _internal_members_size();
}
inline ::Net::Port* VlanMember::mutable_members(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Net.VlanMember.members)
  return _internal_mutable_members()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Net::Port>* VlanMember::mutable_members()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Net.VlanMember.members)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_members();
}
inline const ::Net::Port& VlanMember::members(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Net.VlanMember.members)
  return _internal_members().Get(index);
}
inline ::Net::Port* VlanMember::add_members() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::Net::Port* _add = _internal_mutable_members()->Add();
  // @@protoc_insertion_point(field_add:Net.VlanMember.members)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Net::Port>& VlanMember::members() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Net.VlanMember.members)
  return _internal_members();
}
inline const ::google::protobuf::RepeatedPtrField<::Net::Port>&
VlanMember::_internal_members() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.members_;
}
inline ::google::protobuf::RepeatedPtrField<::Net::Port>*
VlanMember::_internal_mutable_members() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.members_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Net


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_vlan_2eproto_2epb_2eh
